[env]
PORT = "8000"

[tasks.default]
description = "Build wasm"
dependencies = ["build"]

[tasks.build]
description = "Build with wasm-pack"
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"
args = ["build", "--no-typescript", "--target", "web", "--out-name", "package", "--dev"]

[tasks.build-release]
description = "Build with wasm-pack --release"
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"
args = ["build", "--no-typescript", "--target", "web", "--out-name", "package", "--release"]

[tasks.test]
description = "Run tests."
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V", min_version = "0.8.0" }
command = "wasm-pack"
args = ["test", "--node"]

[tasks.serve]
description = "Start server"
install_crate = { crate_name = "microserver", binary = "microserver", test_arg = "-h" }
command = "microserver"
args = ["--port", "${PORT}"]

[tasks.watch]
description = "Build, create wasms, and watch/recompile files for changes"
dependencies = ["build", "create_wasm"]
watch = { ignore_pattern="pkg/*" }