[package]
name = "spotijay"
version = "0.1.0"
authors = ["Håkon H. Lerring <hakon@lerring.no>"]
edition = "2018"

[[bin]]
name = "server"
[[bin]]
name = "client"

[dependencies]
refinery = {version = "0.2.1", features = ["rusqlite"]}
rusqlite = "0.21.0"
