[package]
name = "spotijay"
version = "0.1.0"
authors = ["Håkon H. Lerring <hakon@lerring.no>"]
edition = "2018"

[[bin]]
name = "server"
[[bin]]
name = "client"

[dependencies]
refinery = {version = "0.2.1", features = ["rusqlite"]}
rustorm = {git = "https://github.com/edmellum/rustorm", features = ["with-sqlite"]}
rustorm_dao = {git = "https://github.com/edmellum/rustorm"}
rusqlite = "0.21.0"
log = "0.4"
env_logger = "0.7"
url = "2.1.0"

[dependencies.tungstenite]
version = "0.10.0"
default-features = false
