name: CI
on: [push, pull_request]
jobs:
  ci:
    name: Build release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # Necessary for now for the cargo cache:
    # https://github.com/actions/cache/issues/133#issuecomment-599102035
    - name: Fix ~/.cargo directory permissions
      run: sudo chown -R $(whoami):$(id -ng) ~/.cargo/
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-index-
    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.os }}-cargo-dev-build-target-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-dev-build-target-
    - name: Cache cargo bin
      uses: actions/cache@v1
      with:
        path: ~/.cargo/bin
        key: ${{ runner.os }}-cargo-bin-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-bin-
    - name: Touch env file
      run: touch .env
    - run: sudo apt-get install -y libssl-dev
    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - uses: davidB/rust-cargo-make@v1
    - name: Build main project and webclient
      uses: actions-rs/cargo@v1
      env:
        CLIENT_ID: test
        REDIRECT_URI: https://localhost:8000/callback
        SERVER_URL: localhost:8000
        SERVER_WS_URL: wss://localhost:8000/
      with:
        command: make
        args: build
    - name: Test all projects
      uses: actions-rs/cargo@v1
      env:
        CLIENT_ID: test
        REDIRECT_URI: https://localhost:8000/callback
        SERVER_URL: localhost:8000
        SERVER_WS_URL: wss://localhost:8000/
      with:
        command: make
        args: test